# Generated by Django 3.2.7 on 2021-09-28 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='date',
        ),
    ]
