# Generated by Django 3.2.7 on 2021-09-27 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relation',
            old_name='to_user',
            new_name='follower',
        ),
        migrations.RenameField(
            model_name='relation',
            old_name='from_user',
            new_name='following',
        ),
    ]
